spring:
  application:
    name: preferences
  profiles:
    active: dev

server:
  port: 8081
management:
  health:
    probes:
      enabled: true
  server:
    port: 8081
  endpoints:
    web:
      base-path: "/"

opentracing:
  jaeger:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080
management:
  server:
    port: 8081

opentracing:
  jaeger:
    enabled: true
    service:
      name: preferences
    endpoint: http://jaeger-collector.istio-system.svc:14268/api/traces
    propagation: b3
    sampler_type: const
    sampler_param: 1